server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
      - id: accountModule
        uri: http://localhost:8081/
        predicates:
        - Path=/account/**
      - id: loanModule
        uri: http://localhost:8082/ 
        predicates:
        - Path=/loan/**
      - id: employeeModule
        uri: http://localhost:8084/
        predicates:
        - Path=/employees/**
      - id: userModule
        uri: http://localhost:8086/
        predicates:
        - Path=/users/**
      